### ISSUE TITLE
ffprobe reports junk in mp3 after retag

### ISSUE THREAD

**Issue by genbyte** [polyfloyd/rust-id3#39]
I'm trying to edit some tags on an MP3 file. I'm calling `Tag::set_title` and then `Tag::write_to_path`. I ran ffprobe on a file before and after changing the title, and afterwards it seems to find errors in the tag.
Before:
![2020-05-21-211544](https://user-images.githubusercontent.com/37253114/82624572-88ca6d00-9ba8-11ea-97f4-8323e06259bc.png)
After:
![2020-05-21-211530](https://user-images.githubusercontent.com/37253114/82624580-8d8f2100-9ba8-11ea-9b6f-4088110d2308.png)

After changing the tags using id3, there is "junk" in the file and ffprobe can no longer determine duration. In fact, the before and after differ by about 9 seconds. Furthermore, it seems that the encoding details were lost (noticed "LAME3.99r" missing from the after).

If you have any idea what's causing this, I'd love to help with a fix (or learn how I'm using the library wrong haha).

You can find the code I was using [here](https://github.com/genuinebyte/mptag/blob/master/src/main.rs#L91).

**Comment by polyfloyd** [comment]
Hmm, that's indeed odd. Your code is fine and messing with the MPEG streams is definitely not intended.

I have not had a closer look atm, but I would start investigating `locate_id3v2` in storage.rs. This function determines the size of any existing tag in the file. If it reports a size larger than the tag actually is it will cause proceeding steps to overwrite whatever comes after it.

`PlainWriter` also in storage.rs could also be at fault here. This type is meant to provide safe access to the tag region in the file by just giving callers a `io::Write` to write a whole tag to. It also implements logic for padding.

I'll see if I have time somewhere in the coming week to fix this. Although I'd like to get this fixed ASAP since this seems to be a data destroying bug. Feel free to investigate yourself as well

**Comment by polyfloyd** [comment]
Ok, so I have done some investigating and found out that the tag encoder was writing an incorrect file size in its header by omitting the size of the header itself. This caused `locate_id3v2` to report the header to be smaller than it actually was in subsequent writes, leaving parts of old tags trailing behind the new tag.

I have fixed issue by adding 10, the size of the header to the written size. FFprobe was still not happy about that because it still reported 1 byte of junk. In response, I added a single zero byte at the end of the tag which satisfied FFprobe.

I have pushed a fix to master, please let me know whether this fixes your issue.

**Comment by genuinebyte** [comment]
Unfortunately it did not fix the issue. I'll have a look at the test files and parse the tags by hand (by brain?) to maybe get a clue what's going wrong. I've attached my test files if you need them. `noise_after.mp3` is the file with the modified tags, and `noise.mp3` is the original. [testmp3.zip](https://github.com/polyfloyd/rust-id3/files/4669638/testmp3.zip)

**Comment by genuinebyte** [comment]
It looks like old tag parts are still trailing behind. I'll paste the relevant xxd output below for each file:
```
00000000: 4944 3304 0040 0000 0079 0000 000c 0120  ID3..@...y..... 
00000010: 0501 0647 5815 5449 5432 0000 0006 0000  ...GX.TIT2......
00000020: 004e 6f69 7365 5441 4c42 0000 0009 0000  .NoiseTALB......
00000030: 004e 6f74 5175 6965 7454 434f 4e00 0000  .NotQuietTCON...
00000040: 0600 0000 4e6f 6973 6554 5045 3100 0000  ....NoiseTPE1...
00000050: 0500 0000 5069 6e6b 5459 4552 0000 0005  ....PinkTYER....
00000060: 0000 0032 3032 3054 4452 4300 0000 0500  ...2020TDRC.....
00000070: 0000 3230 3230 5452 434b 0000 0003 0000  ..2020TRCK......
00000080: 0030 31ff fbe0 c400 0000 0000 0000 0000  .01.............
```

After:
```
00000000: 4944 3304 0000 0000 0077 5441 4c42 0000  ID3......wTALB..
00000010: 0009 0000 034e 6f74 5175 6965 7454 434f  .....NotQuietTCO
00000020: 4e00 0000 0600 0003 4e6f 6973 6554 5045  N.......NoiseTPE
00000030: 3100 0000 0500 0003 5069 6e6b 5459 4552  1.......PinkTYER
00000040: 0000 0005 0000 0332 3032 3054 4452 4300  .......2020TDRC.
00000050: 0000 0500 0003 3230 3230 5452 434b 0000  ......2020TRCK..
00000060: 0003 0000 0330 3154 4954 3200 0000 0500  .....01TIT2.....
00000070: 0003 4e6f 7365 0000 004b 0000 0003 0000  ..Nose...K......
00000080: 0030 31ff fbe0 c400 0000 0000 0000 0000  .01.............
```

In the after tag, at `7A`, you can see a stray K from where the TRCK frame used to be. There is also a the track number, 01, starting at byte `81`.

**Comment by polyfloyd** [comment]
I think this is related to how the header is read and written. This logic is duplicated in rust-id3, so I started out with de-duplicating it. Unfortunately I am very low on time and energy due to the crisis so I am not able to fix this any time soon. The `issue-39` branch contains a WIP commit of my current effort.

**Comment by Marekkon5** [comment]
Any progress? I've tried setting 0 padding in `PlainStorage` which fixed the issur when working with tiny test files, but on actual files the bug presists.

**Comment by polyfloyd** [comment]
No, I have not had much time and energy to persue this :/

However, I did de-duplicate the header parsing logic which should make this issue easier to resolve.

**Comment by Marekkon5** [comment]
Hello, I've been just testing it and I found a solution, by comparing it to tag written using Kid3:
- In tag size don't add the header (10) and single byte, but add the file padding, which should be set to 1024-1, instead of 2048.

I'll make PR.
